name: Java CI

on:
  push:
    branches: [main, '**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - uses: mate-academy/auto-approve-action@v2
        if: ${{ github.event_name == 'pull_request' && success() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: mate-academy/auto-reject-action@v2
        if: ${{ github.event_name == 'pull_request' && failure() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
