name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Auto-approve PR
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: mate-academy/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-reject PR
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: mate-academy/auto-reject-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
